// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v0

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	abac "k8s.io/kubernetes/pkg/apis/abac"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddConversionFunc((*Policy)(nil), (*abac.Policy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v0_Policy_To_abac_Policy(a.(*Policy), b.(*abac.Policy), scope)
	}); err != nil {
		return err
	}
	return nil
}
