#!/bin/sh

# This driver implements a tmpfs with a pre-populated file index.html.

FLEX_DUMMY_LOG=${FLEX_DUMMY_LOG:-"/tmp/flex-dummy.log"}

log() {
	printf "$*" >&1
}

debug() {
	echo "$(date) $*" >> "${FLEX_DUMMY_LOG}"
}

domount() {
	debug "domount $@"
	MNTPATH=$1
	mkdir -p ${MNTPATH} >/dev/null 2>&1
	mount -t tmpfs none ${MNTPATH} >/dev/null 2>&1
	echo "Hello from flexvolume!" >> "${MNTPATH}/index.html"
	log "{\"status\":\"Success\"}"
	exit 0
}

unmount() {
	debug "unmount $@"
	MNTPATH=$1
	rm ${MNTPATH}/index.html >/dev/null 2>&1
	umount ${MNTPATH} >/dev/null 2>&1
	log "{\"status\":\"Success\"}"
	exit 0
}

op=$1

if [ "$op" = "init" ]; then
	debug "init $@"
	log "{\"status\":\"Success\",\"capabilities\":{\"attach\":false}}"
	exit 0
fi

shift

case "$op" in
	mount)
		domount $*
		;;
	unmount)
		unmount $*
		;;
	*)
		log "{\"status\":\"Not supported\"}"
		exit 0
esac

exit 1
