// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1 "k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example2/v1"
)

type FakeSecondExampleV1 struct {
	*testing.Fake
}

func (c *FakeSecondExampleV1) TestTypes(namespace string) v1.TestTypeInterface {
	return &FakeTestTypes{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSecondExampleV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
