// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1 "k8s.io/code-generator/_examples/HyphenGroup/clientset/versioned/typed/example/v1"
)

type FakeExampleGroupV1 struct {
	*testing.Fake
}

func (c *FakeExampleGroupV1) ClusterTestTypes() v1.ClusterTestTypeInterface {
	return &FakeClusterTestTypes{c}
}

func (c *FakeExampleGroupV1) TestTypes(namespace string) v1.TestTypeInterface {
	return &FakeTestTypes{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeExampleGroupV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
