// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// RuntimeClassListerExpansion allows custom methods to be added to
// RuntimeClassLister.
type RuntimeClassListerExpansion interface{}
