// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "k8s.io/node-api/pkg/apis/node/v1alpha1"
)

// RuntimeClassLister helps list RuntimeClasses.
type RuntimeClassLister interface {
	// List lists all RuntimeClasses in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.RuntimeClass, err error)
	// Get retrieves the RuntimeClass from the index for a given name.
	Get(name string) (*v1alpha1.RuntimeClass, error)
	RuntimeClassListerExpansion
}

// runtimeClassLister implements the RuntimeClassLister interface.
type runtimeClassLister struct {
	indexer cache.Indexer
}

// NewRuntimeClassLister returns a new RuntimeClassLister.
func NewRuntimeClassLister(indexer cache.Indexer) RuntimeClassLister {
	return &runtimeClassLister{indexer: indexer}
}

// List lists all RuntimeClasses in the indexer.
func (s *runtimeClassLister) List(selector labels.Selector) (ret []*v1alpha1.RuntimeClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RuntimeClass))
	})
	return ret, err
}

// Get retrieves the RuntimeClass from the index for a given name.
func (s *runtimeClassLister) Get(name string) (*v1alpha1.RuntimeClass, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("runtimeclass"), name)
	}
	return obj.(*v1alpha1.RuntimeClass), nil
}
