// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/node-api/pkg/client/clientset/versioned/typed/node/v1alpha1"
)

type FakeNodeV1alpha1 struct {
	*testing.Fake
}

func (c *FakeNodeV1alpha1) RuntimeClasses() v1alpha1.RuntimeClassInterface {
	return &FakeRuntimeClasses{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNodeV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
