// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1beta1 "k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1"
)

type FakeMetricsV1beta1 struct {
	*testing.Fake
}

func (c *FakeMetricsV1beta1) NodeMetricses() v1beta1.NodeMetricsInterface {
	return &FakeNodeMetricses{c}
}

func (c *FakeMetricsV1beta1) PodMetricses(namespace string) v1beta1.PodMetricsInterface {
	return &FakePodMetricses{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMetricsV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
