// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "k8s.io/api/auditregistration/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&v1alpha1.AuditSink{}, func(obj interface{}) { SetObjectDefaults_AuditSink(obj.(*v1alpha1.AuditSink)) })
	scheme.AddTypeDefaultingFunc(&v1alpha1.AuditSinkList{}, func(obj interface{}) { SetObjectDefaults_AuditSinkList(obj.(*v1alpha1.AuditSinkList)) })
	return nil
}

func SetObjectDefaults_AuditSink(in *v1alpha1.AuditSink) {
	SetDefaults_AuditSink(in)
	if in.Spec.Webhook.ClientConfig.Service != nil {
		SetDefaults_ServiceReference(in.Spec.Webhook.ClientConfig.Service)
	}
}

func SetObjectDefaults_AuditSinkList(in *v1alpha1.AuditSinkList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_AuditSink(a)
	}
}
