// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	example2 "k8s.io/code-generator/_examples/apiserver/apis/example2"
)

// TestTypeLister helps list TestTypes.
type TestTypeLister interface {
	// List lists all TestTypes in the indexer.
	List(selector labels.Selector) (ret []*example2.TestType, err error)
	// Get retrieves the TestType from the index for a given name.
	Get(name string) (*example2.TestType, error)
	TestTypeListerExpansion
}

// testTypeLister implements the TestTypeLister interface.
type testTypeLister struct {
	indexer cache.Indexer
}

// NewTestTypeLister returns a new TestTypeLister.
func NewTestTypeLister(indexer cache.Indexer) TestTypeLister {
	return &testTypeLister{indexer: indexer}
}

// List lists all TestTypes in the indexer.
func (s *testTypeLister) List(selector labels.Selector) (ret []*example2.TestType, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*example2.TestType))
	})
	return ret, err
}

// Get retrieves the TestType from the index for a given name.
func (s *testTypeLister) Get(name string) (*example2.TestType, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(example2.Resource("testtype"), name)
	}
	return obj.(*example2.TestType), nil
}
