// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "k8s.io/api/discovery/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&v1alpha1.EndpointSlice{}, func(obj interface{}) { SetObjectDefaults_EndpointSlice(obj.(*v1alpha1.EndpointSlice)) })
	scheme.AddTypeDefaultingFunc(&v1alpha1.EndpointSliceList{}, func(obj interface{}) { SetObjectDefaults_EndpointSliceList(obj.(*v1alpha1.EndpointSliceList)) })
	return nil
}

func SetObjectDefaults_EndpointSlice(in *v1alpha1.EndpointSlice) {
	for i := range in.Ports {
		a := &in.Ports[i]
		SetDefaults_EndpointPort(a)
	}
}

func SetObjectDefaults_EndpointSliceList(in *v1alpha1.EndpointSliceList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_EndpointSlice(a)
	}
}
