// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	internalversion "k8s.io/code-generator/_examples/apiserver/clientset/internalversion/typed/example2/internalversion"
)

type FakeSecondExample struct {
	*testing.Fake
}

func (c *FakeSecondExample) TestTypes() internalversion.TestTypeInterface {
	return &FakeTestTypes{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSecondExample) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
