package testing

import (
	"github.com/stretchr/testify/mock"
	. "k8s.io/kubernetes/pkg/volume"
)

// ORIGINALLY GENERATED BY mockery with hand edits

type MockVolume struct {
	mock.Mock
}

// GetPath provides a mock function with given fields:
func (_m *MockVolume) GetPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetMetrics provides a mock function with given fields:
func (_m *MockVolume) GetMetrics() (*Metrics, error) {
	ret := _m.Called()

	var r0 *Metrics
	if rf, ok := ret.Get(0).(func() *Metrics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Metrics)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
