// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	internalversion "k8s.io/code-generator/_examples/apiserver/clientset/internalversion/typed/example3.io/internalversion"
)

type FakeThirdExample struct {
	*testing.Fake
}

func (c *FakeThirdExample) TestTypes(namespace string) internalversion.TestTypeInterface {
	return &FakeTestTypes{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeThirdExample) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
