FROM BASEIMAGE

USER ContainerAdministrator
ENV chocolateyUseWindowsCompression false
RUN powershell -Command \
    iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); \
    choco feature disable --name showDownloadProgress; \
    powershell -Command choco install bind-toolsonly --version 9.10.3 -y
RUN powershell -Command "\
    wget -uri 'https://github.com/coredns/coredns/releases/download/v1.5.0/coredns_1.5.0_windows_amd64.tgz' -OutFile 'C:\coredns.tgz';\
    tar -xzvf 'C:\coredns.tgz';\
    Remove-Item 'C:\coredns.tgz'"
ADD hostname /bin/hostname.exe
