// Code generated by client-gen. DO NOT EDIT.

package scheme

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	example "k8s.io/code-generator/_examples/apiserver/apis/example/install"
	secondexample "k8s.io/code-generator/_examples/apiserver/apis/example2/install"
	thirdexample "k8s.io/code-generator/_examples/apiserver/apis/example3.io/install"
)

var Scheme = runtime.NewScheme()
var Codecs = serializer.NewCodecFactory(Scheme)
var ParameterCodec = runtime.NewParameterCodec(Scheme)

func init() {
	v1.AddToGroupVersion(Scheme, schema.GroupVersion{Version: "v1"})
	Install(Scheme)
}

// Install registers the API group and adds types to a scheme
func Install(scheme *runtime.Scheme) {
	example.Install(scheme)
	secondexample.Install(scheme)
	thirdexample.Install(scheme)
}
