# The line below points to debian:jessie as of 2019-10-23. The SHA should be
# kept in sycn with debian_jessie definition in the WORKSPACE file.
FROM debian@sha256:e25703ee6ab5b2fac31510323d959cdae31eebdf48e88891c549e55b25ad7e94

COPY kubemark /kubemark
