package phases

import (
	"fmt"

	"github.com/pkg/errors"

	"k8s.io/kubernetes/cmd/kubeadm/app/cmd/options"
	"k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow"
	cmdutil "k8s.io/kubernetes/cmd/kubeadm/app/cmd/util"
	clusterinfophase "k8s.io/kubernetes/cmd/kubeadm/app/phases/bootstraptoken/clusterinfo"
	nodebootstraptokenphase "k8s.io/kubernetes/cmd/kubeadm/app/phases/bootstraptoken/node"
)

var (
	bootstrapTokenLongDesc = cmdutil.LongDesc(`
		Bootstrap tokens are used for establishing bidirectional trust between a node joining
		the cluster and a control-plane node.

		This command makes all the configurations required to make bootstrap tokens works
		and then creates an initial token.
		`)

	bootstrapTokenExamples = cmdutil.Examples(`
		# Make all the bootstrap token configurations and create an initial token, functionally
		# equivalent to what generated by kubeadm init.
		kubeadm init phase bootstrap-token
		`)
)

// NewBootstrapTokenPhase returns the phase to bootstrapToken
func NewBootstrapTokenPhase() workflow.Phase {
	return workflow.Phase{
		Name:    "bootstrap-token",
		Aliases: []string{"bootstraptoken"},
		Short:   "Generates bootstrap tokens used to join a node to a cluster",
		Example: bootstrapTokenExamples,
		Long:    bootstrapTokenLongDesc,
		InheritFlags: []string{
			options.CfgPath,
			options.KubeconfigPath,
			options.SkipTokenPrint,
		},
		Run: runBootstrapToken,
	}
}

// runBootstrapToken 为初始化过程中传入或生成的 bootstrap token 创建 secret 对象, 
// 并为这些 token 设置权限.
func runBootstrapToken(c workflow.RunData) (err error) {
	data, ok := c.(InitData)
	if !ok {
		return errors.New("bootstrap-token phase invoked with an invalid data struct")
	}

	client, err := data.Client()
	if err != nil {
		return err
	}

	if !data.SkipTokenPrint() {
		tokens := data.Tokens()
		if len(tokens) == 1 {
			fmt.Printf("[bootstrap-token] Using token: %s\n", tokens[0])
		} else if len(tokens) > 1 {
			fmt.Printf("[bootstrap-token] Using tokens: %v\n", tokens)
		}
	}

	fmt.Println("[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles")
	// Create the default node bootstrap token
	err = nodebootstraptokenphase.UpdateOrCreateTokens(
		client, false, data.Cfg().BootstrapTokens,
	)
	if err != nil {
		return errors.Wrap(err, "error updating or creating token")
	}
	// Create RBAC rules that makes the bootstrap tokens able to post CSRs
	err = nodebootstraptokenphase.AllowBootstrapTokensToPostCSRs(client)
	if err != nil {
		return errors.Wrap(err, "error allowing bootstrap tokens to post CSRs")
	}
	// Create RBAC rules that makes the bootstrap tokens able to get their CSRs
	// approved automatically
	err = nodebootstraptokenphase.AutoApproveNodeBootstrapTokens(client)
	if err != nil {
		return errors.Wrap(err, "error auto-approving node bootstrap tokens")
	}

	// Create/update RBAC rules that makes the nodes to rotate certificates
	// and get their CSRs approved automatically
	err = nodebootstraptokenphase.AutoApproveNodeCertificateRotation(client)
	if err != nil {
		return err
	}

	// Create the cluster-info ConfigMap with the associated RBAC rules
	err = clusterinfophase.CreateBootstrapConfigMapIfNotExists(
		client, data.KubeConfigPath(),
	)
	if err != nil {
		return errors.Wrap(err, "error creating bootstrap ConfigMap")
	}
	err = clusterinfophase.CreateClusterInfoRBACRules(client)
	if err != nil {
		return errors.Wrap(err, "error creating clusterinfo RBAC rules")
	}
	return nil
}
